package:
  name: q2-rgi
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel

  build:
    - python {{ python }}
    - setuptools
    - versioningit

  run:
    - qiime2 >={{ qiime2 }}
    - "q2-demux >=2025.4.0"
    - "q2-feature-table >=2025.4.0"
    - q2-types >={{ q2_types }}
    - q2templates >={{ q2templates }}
    - rgi
    - tqdm

test:
  requires:
    - parameterized
  imports:
    - q2_rgi
    - qiime2.plugins.rgi
  commands:
    - pytest --pyargs q2_rgi

about:
  home: https://github.com/bokulich-lab/q2-rgi
  license: BSD-3-Clause
  license_family: BSD
