{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-amr
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python=3.8.*
    - setuptools

  run:
    - python=3.8.*
    - qiime2 {{ qiime2_epoch }}.*
    - q2-demux {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2cli {{ qiime2_epoch }}.*
    - rgi
    - tqdm

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_amr
    - qiime2.plugins.amr
  commands:
    - pytest --cov q2_amr --cov-report xml:coverage.xml --pyargs q2_amr

about:
  home: https://github.com/bokulich-lab/q2-amr
  license: BSD-3-Clause
  license_family: BSD
